[workspace]
resolver = "2"
members = [
  "crates/marxml",
  "bindings/node",
]

[workspace.package]
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/thebytefarm/marxml"
homepage = "https://github.com/thebytefarm/marxml"
authors = ["Zac Rosenbauer <me@zrosenbauer.com>"]
